/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/

-- Find total customers by countries
SELECT 
	country, 
	COUNT(customer_key) AS 'Total Customers/Country'
FROM gold.dim_customers 
GROUP BY country
ORDER BY 2 DESC

-- Find total customers by gender
SELECT 
	gender, 
	COUNT(gender) AS 'Total Customers/Gender'
FROM gold.dim_customers 
GROUP BY gender
ORDER BY 2 DESC

-- Find total products by category
SELECT 
	category, 
	COUNT(product_key) AS 'Total Products/Category'
FROM gold.dim_products 
GROUP BY category
ORDER BY 2 DESC

-- What is the average costs in each category?
SELECT 
	category, 
	AVG(cost) AS 'Average Cost/Category'
FROM gold.dim_products 
GROUP BY category
ORDER BY 2 DESC

-- What is the total revenue generated for each category?
SELECT 
	dp.category,
	SUM(sale_amount) AS 'Total Revenue/Category'
FROM gold.fact_sales fs
LEFT JOIN gold.dim_products dp
ON fs.product_key = dp.product_key
GROUP BY dp.category
ORDER BY 2 DESC

-- What is the total revenue generated by each customer?
SELECT 
	dc.customer_key,
	dc.first_name,
	dc.last_name,
	SUM(sale_amount) AS 'Total Revenue/Customer'
FROM gold.fact_sales fs
LEFT JOIN gold.dim_customers dc
ON fs.customer_key = dc.customer_key
GROUP BY dc.customer_key, dc.first_name, dc.last_name
ORDER BY 4 DESC

-- What is the distribution of sold items across countries?
SELECT 
	dc.country,
	SUM(quantity) AS 'Total Quantity/Country'
FROM gold.fact_sales fs
LEFT JOIN gold.dim_customers dc
ON fs.customer_key = dc.customer_key
GROUP BY dc.country
ORDER BY 2 DESC